//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace Check.sutherlandsmbpov_toolCreatingIncident {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceNowSoap", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class ServiceNow_u_sgs_tool_creating_incident : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKeysOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRecordsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceNow_u_sgs_tool_creating_incident() {
            this.Url = global::Check.Properties.Settings.Default.Check_sutherlandsmbpov_toolCreatingIncident_ServiceNow_u_sgs_tool_creating_incident;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertCompletedEventHandler insertCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event deleteMultipleCompletedEventHandler deleteMultipleCompleted;
        
        /// <remarks/>
        public event getKeysCompletedEventHandler getKeysCompleted;
        
        /// <remarks/>
        public event deleteRecordCompletedEventHandler deleteRecordCompleted;
        
        /// <remarks/>
        public event getCompletedEventHandler getCompleted;
        
        /// <remarks/>
        public event getRecordsCompletedEventHandler getRecordsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/insert", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("insertResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        public insertResponse insert([System.Xml.Serialization.XmlElementAttribute("insert", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] insert insert1) {
            object[] results = this.Invoke("insert", new object[] {
                        insert1});
            return ((insertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void insertAsync(insert insert1) {
            this.insertAsync(insert1, null);
        }
        
        /// <remarks/>
        public void insertAsync(insert insert1, object userState) {
            if ((this.insertOperationCompleted == null)) {
                this.insertOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertOperationCompleted);
            }
            this.InvokeAsync("insert", new object[] {
                        insert1}, this.insertOperationCompleted, userState);
        }
        
        private void OninsertOperationCompleted(object arg) {
            if ((this.insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertCompleted(this, new insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/update", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        public updateResponse update([System.Xml.Serialization.XmlElementAttribute("update", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] update update1) {
            object[] results = this.Invoke("update", new object[] {
                        update1});
            return ((updateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(update update1) {
            this.updateAsync(update1, null);
        }
        
        /// <remarks/>
        public void updateAsync(update update1, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        update1}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/deleteMultiple", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("deleteMultipleResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        public deleteMultipleResponse deleteMultiple([System.Xml.Serialization.XmlElementAttribute("deleteMultiple", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] deleteMultiple deleteMultiple1) {
            object[] results = this.Invoke("deleteMultiple", new object[] {
                        deleteMultiple1});
            return ((deleteMultipleResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteMultipleAsync(deleteMultiple deleteMultiple1) {
            this.deleteMultipleAsync(deleteMultiple1, null);
        }
        
        /// <remarks/>
        public void deleteMultipleAsync(deleteMultiple deleteMultiple1, object userState) {
            if ((this.deleteMultipleOperationCompleted == null)) {
                this.deleteMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteMultipleOperationCompleted);
            }
            this.InvokeAsync("deleteMultiple", new object[] {
                        deleteMultiple1}, this.deleteMultipleOperationCompleted, userState);
        }
        
        private void OndeleteMultipleOperationCompleted(object arg) {
            if ((this.deleteMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteMultipleCompleted(this, new deleteMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/getKeys", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getKeysResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        public getKeysResponse getKeys([System.Xml.Serialization.XmlElementAttribute("getKeys", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] getKeys getKeys1) {
            object[] results = this.Invoke("getKeys", new object[] {
                        getKeys1});
            return ((getKeysResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getKeysAsync(getKeys getKeys1) {
            this.getKeysAsync(getKeys1, null);
        }
        
        /// <remarks/>
        public void getKeysAsync(getKeys getKeys1, object userState) {
            if ((this.getKeysOperationCompleted == null)) {
                this.getKeysOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKeysOperationCompleted);
            }
            this.InvokeAsync("getKeys", new object[] {
                        getKeys1}, this.getKeysOperationCompleted, userState);
        }
        
        private void OngetKeysOperationCompleted(object arg) {
            if ((this.getKeysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKeysCompleted(this, new getKeysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/deleteRecord", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("deleteRecordResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        public deleteRecordResponse deleteRecord([System.Xml.Serialization.XmlElementAttribute("deleteRecord", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] deleteRecord deleteRecord1) {
            object[] results = this.Invoke("deleteRecord", new object[] {
                        deleteRecord1});
            return ((deleteRecordResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteRecordAsync(deleteRecord deleteRecord1) {
            this.deleteRecordAsync(deleteRecord1, null);
        }
        
        /// <remarks/>
        public void deleteRecordAsync(deleteRecord deleteRecord1, object userState) {
            if ((this.deleteRecordOperationCompleted == null)) {
                this.deleteRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRecordOperationCompleted);
            }
            this.InvokeAsync("deleteRecord", new object[] {
                        deleteRecord1}, this.deleteRecordOperationCompleted, userState);
        }
        
        private void OndeleteRecordOperationCompleted(object arg) {
            if ((this.deleteRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRecordCompleted(this, new deleteRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/get", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        public getResponse get([System.Xml.Serialization.XmlElementAttribute("get", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] get get1) {
            object[] results = this.Invoke("get", new object[] {
                        get1});
            return ((getResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAsync(get get1) {
            this.getAsync(get1, null);
        }
        
        /// <remarks/>
        public void getAsync(get get1, object userState) {
            if ((this.getOperationCompleted == null)) {
                this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
            }
            this.InvokeAsync("get", new object[] {
                        get1}, this.getOperationCompleted, userState);
        }
        
        private void OngetOperationCompleted(object arg) {
            if ((this.getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.service-now.com/u_sgs_tool_creating_incident/getRecords", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getRecordsResponse", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("getRecordsResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public getRecordsResponseGetRecordsResult[] getRecords([System.Xml.Serialization.XmlElementAttribute("getRecords", Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")] getRecords getRecords1) {
            object[] results = this.Invoke("getRecords", new object[] {
                        getRecords1});
            return ((getRecordsResponseGetRecordsResult[])(results[0]));
        }
        
        /// <remarks/>
        public void getRecordsAsync(getRecords getRecords1) {
            this.getRecordsAsync(getRecords1, null);
        }
        
        /// <remarks/>
        public void getRecordsAsync(getRecords getRecords1, object userState) {
            if ((this.getRecordsOperationCompleted == null)) {
                this.getRecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRecordsOperationCompleted);
            }
            this.InvokeAsync("getRecords", new object[] {
                        getRecords1}, this.getRecordsOperationCompleted, userState);
        }
        
        private void OngetRecordsOperationCompleted(object arg) {
            if ((this.getRecordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRecordsCompleted(this, new getRecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class insert {
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class insertResponse {
        
        private string sys_idField;
        
        private string tableField;
        
        private string display_nameField;
        
        private string display_valueField;
        
        private string statusField;
        
        private string status_messageField;
        
        private string error_messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                this.display_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string display_value {
            get {
                return this.display_valueField;
            }
            set {
                this.display_valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status_message {
            get {
                return this.status_messageField;
            }
            set {
                this.status_messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error_message {
            get {
                return this.error_messageField;
            }
            set {
                this.error_messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class update {
        
        private string sys_idField;
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class updateResponse {
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class deleteMultiple {
        
        private string sys_class_nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_import_rowField;
        
        private string sys_import_setField;
        
        private string sys_import_stateField;
        
        private string sys_import_state_commentField;
        
        private string sys_mod_countField;
        
        private string sys_row_errorField;
        
        private string sys_target_sys_idField;
        
        private string sys_target_tableField;
        
        private string sys_transform_mapField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_class_name {
            get {
                return this.sys_class_nameField;
            }
            set {
                this.sys_class_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_import_row {
            get {
                return this.sys_import_rowField;
            }
            set {
                this.sys_import_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_set {
            get {
                return this.sys_import_setField;
            }
            set {
                this.sys_import_setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state {
            get {
                return this.sys_import_stateField;
            }
            set {
                this.sys_import_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state_comment {
            get {
                return this.sys_import_state_commentField;
            }
            set {
                this.sys_import_state_commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_row_error {
            get {
                return this.sys_row_errorField;
            }
            set {
                this.sys_row_errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_sys_id {
            get {
                return this.sys_target_sys_idField;
            }
            set {
                this.sys_target_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_table {
            get {
                return this.sys_target_tableField;
            }
            set {
                this.sys_target_tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_transform_map {
            get {
                return this.sys_transform_mapField;
            }
            set {
                this.sys_transform_mapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class deleteMultipleResponse {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class getKeys {
        
        private string sys_class_nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_import_rowField;
        
        private string sys_import_setField;
        
        private string sys_import_stateField;
        
        private string sys_import_state_commentField;
        
        private string sys_mod_countField;
        
        private string sys_row_errorField;
        
        private string sys_target_sys_idField;
        
        private string sys_target_tableField;
        
        private string sys_transform_mapField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        private string @__use_viewField;
        
        private string @__encoded_queryField;
        
        private string @__limitField;
        
        private string @__first_rowField;
        
        private string @__last_rowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_class_name {
            get {
                return this.sys_class_nameField;
            }
            set {
                this.sys_class_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_import_row {
            get {
                return this.sys_import_rowField;
            }
            set {
                this.sys_import_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_set {
            get {
                return this.sys_import_setField;
            }
            set {
                this.sys_import_setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state {
            get {
                return this.sys_import_stateField;
            }
            set {
                this.sys_import_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state_comment {
            get {
                return this.sys_import_state_commentField;
            }
            set {
                this.sys_import_state_commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_row_error {
            get {
                return this.sys_row_errorField;
            }
            set {
                this.sys_row_errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_sys_id {
            get {
                return this.sys_target_sys_idField;
            }
            set {
                this.sys_target_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_table {
            get {
                return this.sys_target_tableField;
            }
            set {
                this.sys_target_tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_transform_map {
            get {
                return this.sys_transform_mapField;
            }
            set {
                this.sys_transform_mapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__encoded_query {
            get {
                return this.@__encoded_queryField;
            }
            set {
                this.@__encoded_queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__limit {
            get {
                return this.@__limitField;
            }
            set {
                this.@__limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__first_row {
            get {
                return this.@__first_rowField;
            }
            set {
                this.@__first_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__last_row {
            get {
                return this.@__last_rowField;
            }
            set {
                this.@__last_rowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class getKeysResponse {
        
        private string[] sys_idField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sys_id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class deleteRecord {
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class deleteRecordResponse {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class get {
        
        private string sys_idField;
        
        private string @__use_viewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class getResponse {
        
        private string sys_class_nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_import_rowField;
        
        private string sys_import_setField;
        
        private string sys_import_stateField;
        
        private string sys_import_state_commentField;
        
        private string sys_mod_countField;
        
        private string sys_row_errorField;
        
        private string sys_target_sys_idField;
        
        private string sys_target_tableField;
        
        private string sys_transform_mapField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_class_name {
            get {
                return this.sys_class_nameField;
            }
            set {
                this.sys_class_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_import_row {
            get {
                return this.sys_import_rowField;
            }
            set {
                this.sys_import_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_set {
            get {
                return this.sys_import_setField;
            }
            set {
                this.sys_import_setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state {
            get {
                return this.sys_import_stateField;
            }
            set {
                this.sys_import_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state_comment {
            get {
                return this.sys_import_state_commentField;
            }
            set {
                this.sys_import_state_commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_row_error {
            get {
                return this.sys_row_errorField;
            }
            set {
                this.sys_row_errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_sys_id {
            get {
                return this.sys_target_sys_idField;
            }
            set {
                this.sys_target_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_table {
            get {
                return this.sys_target_tableField;
            }
            set {
                this.sys_target_tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_transform_map {
            get {
                return this.sys_transform_mapField;
            }
            set {
                this.sys_transform_mapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class getRecords {
        
        private string sys_class_nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_import_rowField;
        
        private string sys_import_setField;
        
        private string sys_import_stateField;
        
        private string sys_import_state_commentField;
        
        private string sys_mod_countField;
        
        private string sys_row_errorField;
        
        private string sys_target_sys_idField;
        
        private string sys_target_tableField;
        
        private string sys_transform_mapField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        private string @__use_viewField;
        
        private string @__encoded_queryField;
        
        private string @__limitField;
        
        private string @__first_rowField;
        
        private string @__last_rowField;
        
        private string @__order_byField;
        
        private string @__order_by_descField;
        
        private string @__exclude_columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_class_name {
            get {
                return this.sys_class_nameField;
            }
            set {
                this.sys_class_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_import_row {
            get {
                return this.sys_import_rowField;
            }
            set {
                this.sys_import_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_set {
            get {
                return this.sys_import_setField;
            }
            set {
                this.sys_import_setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state {
            get {
                return this.sys_import_stateField;
            }
            set {
                this.sys_import_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state_comment {
            get {
                return this.sys_import_state_commentField;
            }
            set {
                this.sys_import_state_commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_row_error {
            get {
                return this.sys_row_errorField;
            }
            set {
                this.sys_row_errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_sys_id {
            get {
                return this.sys_target_sys_idField;
            }
            set {
                this.sys_target_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_table {
            get {
                return this.sys_target_tableField;
            }
            set {
                this.sys_target_tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_transform_map {
            get {
                return this.sys_transform_mapField;
            }
            set {
                this.sys_transform_mapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__encoded_query {
            get {
                return this.@__encoded_queryField;
            }
            set {
                this.@__encoded_queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__limit {
            get {
                return this.@__limitField;
            }
            set {
                this.@__limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__first_row {
            get {
                return this.@__first_rowField;
            }
            set {
                this.@__first_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__last_row {
            get {
                return this.@__last_rowField;
            }
            set {
                this.@__last_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__order_by {
            get {
                return this.@__order_byField;
            }
            set {
                this.@__order_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__order_by_desc {
            get {
                return this.@__order_by_descField;
            }
            set {
                this.@__order_by_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @__exclude_columns {
            get {
                return this.@__exclude_columnsField;
            }
            set {
                this.@__exclude_columnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/u_sgs_tool_creating_incident")]
    public partial class getRecordsResponseGetRecordsResult {
        
        private string sys_class_nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_import_rowField;
        
        private string sys_import_setField;
        
        private string sys_import_stateField;
        
        private string sys_import_state_commentField;
        
        private string sys_mod_countField;
        
        private string sys_row_errorField;
        
        private string sys_target_sys_idField;
        
        private string sys_target_tableField;
        
        private string sys_transform_mapField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string u_impactField;
        
        private string u_issues_explained_in_detailField;
        
        private string u_scan_idField;
        
        private string u_short_descriptionField;
        
        private string u_user_name_re_ting_the_issueField;
        
        private string u_users_company_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_class_name {
            get {
                return this.sys_class_nameField;
            }
            set {
                this.sys_class_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_import_row {
            get {
                return this.sys_import_rowField;
            }
            set {
                this.sys_import_rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_set {
            get {
                return this.sys_import_setField;
            }
            set {
                this.sys_import_setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state {
            get {
                return this.sys_import_stateField;
            }
            set {
                this.sys_import_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_import_state_comment {
            get {
                return this.sys_import_state_commentField;
            }
            set {
                this.sys_import_state_commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_row_error {
            get {
                return this.sys_row_errorField;
            }
            set {
                this.sys_row_errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_sys_id {
            get {
                return this.sys_target_sys_idField;
            }
            set {
                this.sys_target_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_target_table {
            get {
                return this.sys_target_tableField;
            }
            set {
                this.sys_target_tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_transform_map {
            get {
                return this.sys_transform_mapField;
            }
            set {
                this.sys_transform_mapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_impact {
            get {
                return this.u_impactField;
            }
            set {
                this.u_impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_issues_explained_in_detail {
            get {
                return this.u_issues_explained_in_detailField;
            }
            set {
                this.u_issues_explained_in_detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_scan_id {
            get {
                return this.u_scan_idField;
            }
            set {
                this.u_scan_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_short_description {
            get {
                return this.u_short_descriptionField;
            }
            set {
                this.u_short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_user_name_re_ting_the_issue {
            get {
                return this.u_user_name_re_ting_the_issueField;
            }
            set {
                this.u_user_name_re_ting_the_issueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string u_users_company_name {
            get {
                return this.u_users_company_nameField;
            }
            set {
                this.u_users_company_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertCompletedEventHandler(object sender, insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public insertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((insertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public updateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((updateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteMultipleCompletedEventHandler(object sender, deleteMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public deleteMultipleResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((deleteMultipleResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getKeysCompletedEventHandler(object sender, getKeysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKeysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKeysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getKeysResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getKeysResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteRecordCompletedEventHandler(object sender, deleteRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public deleteRecordResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((deleteRecordResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRecordsCompletedEventHandler(object sender, getRecordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getRecordsResponseGetRecordsResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getRecordsResponseGetRecordsResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591